### ISSUE TITLE
MOTION detection and live update on python plots.

### ISSUE THREAD

**Issue by NidhiSultan** [zephirl/BrainViz#1]
Hi BrainViz, 
I am trying to analyze and put data from eeg to a python plot live but facing some issues like not updating live.
Can you please help me with how did you guys achieve it.

Regards
Nidhi

**Comment by zephirl** [comment]
Hi Nidhi,
Did you take a look at the Emotiv LSL software to communicate between the brain-ware and a python script? https://github.com/Emotiv/labstreaminglayer/tree/master/examples/python

To get the live data, we pull data at every tilmestep from the LSL stream that we set up with EmotivPro to which our EEG headset is connected to via Bluetooth on our computer.

Best,
Zéphir

**Comment by NidhiSultan** [comment]
Hi Zephirl, 
I was able to resolve the issue. Thankyou for replying. :)
